### ISSUE TITLE
IDF version selection--odd behavior (VSC-1341)

### ISSUE THREAD

**Issue by mtraven** [espressif/vscode-esp-idf-extension#1179]
### OS

Windows

### Operating System version

windows 10

### Visual Studio Code version

1.88.0

### ESP-IDF version

4.4.7

### Python version

3.11.3

### Doctor command output

n/a

### Extension

not sure what you want here, the log is very log & probably totally irreverent.  if you need something from it, just ask.

### Description

-when making an example file in, say IDF 5.2:  make the example file(5.2 already selected), the project will be in 4.4.7 (for me)--I believe that to be the first framework I added & thus some sort of default. 
-correcting this ( configuring IDF @ the workfolder scope via existing setups), reveals additional odd behavior: Say I select 5.2 from my existing setups. the top half (framework) says its loading the version thats already in play (4.4.7), the bottom half(tools) says its loading the 5.2 tools! And that IS exactly what it does (verified @ path settings). 

-Running the config a second time, selecting IDF5.2 activates 5.2 framework AND tools....everything works fine.

**NOTE : please bring back the save scope selection on the configuration menu, that would be handy, not sure why you changed it to just a read out. (i know how to change the settings, its just inconvenient )

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
One question, what is the current ESP-IDF version when you make an example and how you make an example ? Could you provide some steps to reproduce.

Remember that workspace folder settings override any global user settings.

**Comment by mtraven** [comment]
yes, I think I understand the scope stuff now, thats how I want it....I need to be able to have 2 vscode windows open with projects in different frameworks.  I'm working with 5.2.1 & 4.4.7 concurrently.

I did a few more experiments before responding, I think I worked out a few more things.  I'm less convinced its a bug & more that it just doesn't work the way I(personally) want it too.  I'll let you be the judge of that.

I think the real issue with make new projects, whilst configuring at the workspace folder level, there is no workspace folder at the time of creation.  It seems that the new project takes on whatever framework was last set when configured in the GLOBAL scope.   I know you said workspace folder overrides user, but I dont think the workspace folder is actually being applied.  I think there needs to be a better way to choose your framework, on the folder level, when starting from templates / examples.

if there is a bug, its that when changing frameworks, @ scope= workspace folder, one has to run the config twice to have it take effect.  You should be able to reproduce that by:

1. setting save scope = workplace folder
2. command->idf configure ->existing setups -> select a different framework
3. watch the screen closely (i screen recorded it), on the top half you still the old IDF version being set, while the bottom half shows the tools for the new framework being loaded.
4. at this point, confirm it wont compile in the newly selected framework
5. run step 2 again, EXACTLY the same.  Both the framework & tools for the new framework with be active.

hope I'm giving you what you need, I'm new to IDF, not a programmer and this my first bug report.  Just wanna help make things better.

**Comment by brianignacio5** [comment]
I tried reproducing on Windows 10 and I observe the following:

1) The UI of setup wizard does indeed show the old IDF_PATH version, it is probably because the UI is not updated to the new chosen existing setup values and that is why is showing old value. **Will update this in a bug fix PR**
2) After choosing the new setup, I run the `ESP-IDF: Doctor Command` and I see that new chosen existing setup values are shown in report. Same for workspace folder `.vscode/settings.json`.
3) With regards to not being able to compile, I've noticed it could be because an existing build directory created with older version is there, so you need to clean the build directory (like with `ESP-IDF: Full Clean` command) and try again. 

It could be due to the code itself being dependent to specific ESP-IDF version. For example, you can notice that the blink example for ESP-IDF 4.4.x is different from 5.2.x with different dependencies (for example esp-idf led_strip component). So version changes can make the code not usable.
