### ISSUE TITLE
vscode使用uart+gdb调试 (VSC-1494)

### ISSUE THREAD

**Issue by ysni** [espressif/vscode-esp-idf-extension#1318]
### OS

Linux

### Operating System version

20.0.4

### ESP-IDF version

5.0.6

### Python version

3.8.10

### Doctor command output

idf无输出,还没进入到程序,
<img width="1089" alt="截屏2024-09-25 13 10 10" src="https://github.com/user-attachments/assets/e648bb2e-5b8e-46f7-baec-6c5c3dda49ce">

### Description

先要使用vscode进行断点调试,idf.py monitor里使用ctr+c可以进行断点调试,可是vscode里点击调试连不上/dev/ttyUSB0,终端直接执行gdb,也连不上
<img width="846" alt="截屏2024-09-25 13 02 55" src="https://github.com/user-attachments/assets/98613662-2cff-45cf-aa78-e6ff03381650">
<img width="255" alt="截屏2024-09-25 13 04 25" src="https://github.com/user-attachments/assets/abc9d823-3a80-4427-87c0-65f23e44f5da">
<img width="458" alt="截屏2024-09-25 13 15 00" src="https://github.com/user-attachments/assets/b8d7dde1-e194-4ff1-86fd-501ac45f1dbf">

### Debug Message

```plain
Remote debugging using /dev/ttyUSB0
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Are you using this extension ? Have you tried using our Eclipse CDT debug adapter configuration as shown here:

https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/DEBUGGING.md

If you are not using our extension and only using the Microsoft C/C++ extension, check in the previous documentation a suggested configuration for `cppdbg`. Since we do not maintain this extension, that is the best we can do.

**Comment by brianignacio5** [comment]
Closing this issue for lack of response. Comment here if you need more help.
