### ISSUE TITLE
OpenoOCD  start/stop API (VSC-436)

### ISSUE THREAD

**Issue by simark1979** [espressif/vscode-esp-idf-extension#167]
Is it possible to start/stop openocd from VSCode tasks via your extension API?
If I start OpenoOCD from my python script, your extension doesn`t update his state in status bar.
So it`s much preferable to use native extension`s command.

**Comment by pwmb** [comment]
We already have a [task](https://github.com/espressif/vscode-esp-idf-extension/blob/c3e6accf1f9373eec87dc08a9f2a47026d3b78f5/templates/.vscode/tasks.json#L157) for openocd also we have command for start/stop OpenOCD, i.e, `espIdf.openocd`, which is tied to the status bar.

Status bar item is not reactive, which means that it won't update if openocd is launched from elsewhere in the system, but since we use `tcl` via `http` to talk to openocd, as long as your tcl port remains unchanged i.e., `6666`.
