### ISSUE TITLE
C++ extension include path for Windows (VSC-228)

### ISSUE THREAD

**Issue by jankrejci** [espressif/vscode-esp-idf-extension#26]
There are underlined include directives under the windows environment. It would be great to add include paths to c_cpp_properities.json

```
"includePath": [
    "${config:idf.espIdfPathWin}/components/**",
    "${config:idf.espIdfPath}/components/**",
    "build/config"
 ],
```
there are both include paths for Linux and Windows, also the build/config is needed otherwise "portTICK_PERIOD_MS" is underlined (don't know why)

Windows 10, VScode 1.41.1, Extension 0.13, ESP-IDP 4.0

**Comment by bitmakk** [comment]
The portTICK_PERIOD_MS macro comes from the SDKconfig, because it depends on the CPU clock freq, and the sdkconfig location is out of your vscode search paths.
"build/config" : it may be wrong, because it is not an absolute path, and may not contain every file you need. I would replace it with: ${workspaceFolder}/** so it scans the components directory as well (if you use cmake include paths, the vscode may not be able to resolve the include), and the build directory as well. 
A full rebuild may be required.
