### ISSUE TITLE
[Bug Report]: esp-idf extension should use previous downloaded files using checksums. (VSC-546)

### ISSUE THREAD

**Issue by dangbinghoo** [espressif/vscode-esp-idf-extension#292]
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [x] Make sure you have searched for existing bugs and features request before you post an issue.
- [x] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [x] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
when esp-idf extension installing idf and tools, it just ignored previous already downloaded files, this is wasting of time as IDF installing and settingup may just failed by networks connection lost or unaviable. the plugin need to check already downloaded file using checksum code, if that match, just use the file rather download again.

**To Reproduce**
just use the plugin to do a new install after a failed install(the python package downloading was timed out).

**Expected behavior**
the plugin should use previous downloaded files

**Screenshots**
no need to add this, it's super clear.

**Environment (please complete the following information):**

- OS Name & Version: any OS, tired on linux and windows 10.
- VSCode Version: any
- ESP-IDF Version: 0.6.0
- Python Version:  3.9.1

**Comment by brianignacio5** [comment]
Have you taken a look at the code ? Please take a look at [DownloadManager.ts](https://github.com/espressif/vscode-esp-idf-extension/blob/03db8d3ede4766845191fa4b3b44890412f906a2/src/downloadManager.ts#L103) we do take a look at ESP-IDF tools packages checksum based on `$IDF_PATH/tools.json` metadata. What happens is that tools are extracted again, just to comply with `$IDF_PATH/idf_tools.py` behavior.

For Python packages, we use `pip install -r requirements.txt` as a nodeJS child process and for ESP-IDF there is some git clone mechanism for GitHub master. ESP-IDF release checksum is something we definitely have to implement at some point.

I'm closing this issue since this is a non issue.
