### ISSUE TITLE
IDF select port can not change port (VSC-793)

### ISSUE THREAD

**Issue by edieruby** [espressif/vscode-esp-idf-extension#579]
- OS Name & Version:  windows10
- VSCode Version: 1.62.3
- ESP-IDF Version: 4.3.1

Port changed from COM6 to COM3, but it not works.

![image](https://user-images.githubusercontent.com/8832188/142994362-3cce5f88-eb24-42ee-8d6a-268af627cb93.png)
![image](https://user-images.githubusercontent.com/8832188/142994392-7683b2dd-62f5-4174-80ba-2f5446161f68.png)
![image](https://user-images.githubusercontent.com/8832188/142994403-017bf66b-6cf0-4329-b9b9-4c2fd9305cbe.png)
![image](https://user-images.githubusercontent.com/8832188/142994452-7c921c06-39e7-483e-b0a3-bcc53f100822.png)
![image](https://user-images.githubusercontent.com/8832188/142994529-662b1da0-9ed8-4d71-8089-30840a2c8c3a.png)

**Comment by brianignacio5** [comment]
When you use the `ESP-IDF: Select port to use` command, the `idf.port` is updated. But the thing is, there is another setting called `idf.saveScope` which define where is the setting saved (User, Workspace or Workspace folder). Probably your project's .vscode/settings.json has a `idf.port` setting that overrides the global user settings (which is probably the one being updated). More about this in the [multiple projects documentation](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/MULTI_PROJECTS.md).

In the GitHub master, we had updated so that `idf.port` is updated to the workspace folder only to avoid this issue.
Please try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/115914250.zip) to test it.

**Comment by brianignacio5** [comment]
Closing this issue for lack of response, comment here if you still have additional issues.

**Comment by moefear85** [comment]
I've recently begun facing this problem. idf.port in settings.json is set to /dev/ttyACM2. It is not set in the ".code-workspace" file. Yet still the extension is always trying to use /dev/ttyUSB1 when flashing, which leads to errors. I explicitly select the project I'm working on every time I update the port, and the extension indicates it changed successfully. but it still keeps using the wrong port. Infact, this issue also happens when I select the mcu type.
