### ISSUE TITLE
[Feature Request]: Include managed_components in full clean (VSC-952)

### ISSUE THREAD

**Issue by schieberegister** [espressif/vscode-esp-idf-extension#785]
**Is your feature request related to a problem? Please describe.**
When running a full clean via VSCode command, the managed_componets folder used by idf_component_manager isn't cleared.

**Describe the solution you'd like**
Would it be viable to delete it as well when running the full clean command?

**Describe alternatives you've considered**
The Alternative is to delete the folder manually.

**Additional context**
Sometimes I change files in managed_components and build to quickly and dirtily test a minor tweak. Would be awesome being able to clean up that mess with one command.

Thank you

**Comment by brianignacio5** [comment]
Actually the content of `managed_components` should not be modified by user as defined in [IDF Component Manager](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html#using-with-a-project) so it shouldn't delete this folder by default (since most components would be pull from Component Registry without modification by default) but having the choice should be nice so adding `idf.deleteComponentsOnFullClean` configuration setting to delete this folder when `ESP-IDF: Full clean project` command is executed, which is `false` by default.
