### ISSUE TITLE
After doing a Build, Compiler Warnings are removed from "PROBLEM" tab (VSC-1009)

### ISSUE THREAD

**Issue by Uvamosk** [espressif/vscode-esp-idf-extension#844]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.73.1

### ESP-IDF version

4.4.3

### Python version

3.8.7

### Doctor command output

N/A

### Description

This issue has existed since 1.4 for me. I was thinking it would be solved in 1.5

When I do a build the "PROBLEMS" tab will show there are 7 Compiler Warnings (IE: A var is unused) after the build is complete this tab will then have all of its contents removed and say 0 problems. 

 Then I can go to the "ESP-IDF Build Task " which is yellow and it will show all my warnings that I then have to dig through and go look up each line number. 
 
 The only time the contents of "PROBLEMS" stay is when there is a actual error. 

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
The issue is the following in vscode.

There are 2 tasks being run sequentially. The compile task and the build task. As long as the compile task doesn't produce an error (exit code != 0) the build task will run. The thing is that tasks replace existing warning in vscode problems tab and AFAIK there is no way an extension developer can persist those error messages.
